-- ============================================================
-- Layal Alshaikh — CMS expansion: Announcements + Site Settings
-- Run this ONCE in Supabase → SQL Editor → New query → Run.
-- Safe to re-run (uses IF NOT EXISTS / ON CONFLICT).
-- ============================================================

-- ---------- ANNOUNCEMENTS (banner offers / news) ----------
create table if not exists public.announcements (
  id          bigint generated by default as identity primary key,
  message     text not null,
  link        text,
  link_label  text,
  active      boolean not null default true,
  sort        int not null default 0,
  created_at  timestamptz not null default now()
);
alter table public.announcements enable row level security;

drop policy if exists "announcements public read" on public.announcements;
create policy "announcements public read" on public.announcements
  for select using (true);

drop policy if exists "announcements admin write" on public.announcements;
create policy "announcements admin write" on public.announcements
  for all to authenticated using (true) with check (true);

-- ---------- SITE SETTINGS (key/value editable content) ----------
create table if not exists public.site_settings (
  key   text primary key,
  value text
);
alter table public.site_settings enable row level security;

drop policy if exists "settings public read" on public.site_settings;
create policy "settings public read" on public.site_settings
  for select using (true);

drop policy if exists "settings admin write" on public.site_settings;
create policy "settings admin write" on public.site_settings
  for all to authenticated using (true) with check (true);

-- Seed the editable contact details (only if not already present)
insert into public.site_settings (key, value) values
  ('phone',     '+974 1234 5678'),
  ('email',     'info@layalalshaikhgroup.com'),
  ('whatsapp',  '97412345678'),
  ('address',   'West Bay, Doha, Qatar'),
  ('hours',     'Sun – Thu: 8:00 AM – 6:00 PM'),
  ('instagram', ''),
  ('linkedin',  ''),
  ('hero_title','Find the Place You''ll Call Home'),
  ('hero_sub',  'For twenty years we''ve helped over 1,200 families find more than a house — a place to feel safe, put down roots, and truly belong.')
on conflict (key) do nothing;
