-- ============================================================
-- Layal Alshaikh Group — Supabase database setup
-- HOW TO RUN: Supabase Dashboard → SQL Editor → New query →
--             paste all of this → Run.  (Safe to re-run.)
-- ============================================================

-- 1) PROPERTIES (villas / apartments / penthouses / commercial)
create table if not exists public.villas (
  id          bigint generated by default as identity primary key,
  name        text not null,
  type        text   default 'Villa',
  location    text,
  price       numeric default 0,
  beds        int    default 0,
  baths       int    default 0,
  area        int    default 0,
  status      text   default 'live',     -- 'live' shows on the site, 'draft' is hidden
  image_url   text,
  sort        int    default 0,
  created_at  timestamptz default now()
);

-- 2) GALLERY images
create table if not exists public.gallery (
  id          bigint generated by default as identity primary key,
  image_url   text not null,
  category    text default 'exterior',   -- exterior | interior | aerial
  caption     text,
  sort        int  default 0,
  created_at  timestamptz default now()
);

-- ============================================================
-- Row Level Security: anyone can READ, only a logged-in admin can WRITE
-- ============================================================
alter table public.villas  enable row level security;
alter table public.gallery enable row level security;

drop policy if exists "public read villas"  on public.villas;
drop policy if exists "public read gallery" on public.gallery;
drop policy if exists "admin write villas"  on public.villas;
drop policy if exists "admin write gallery" on public.gallery;

create policy "public read villas"  on public.villas  for select using (true);
create policy "public read gallery" on public.gallery for select using (true);
create policy "admin write villas"  on public.villas  for all to authenticated using (true) with check (true);
create policy "admin write gallery" on public.gallery for all to authenticated using (true) with check (true);

-- ============================================================
-- Storage bucket "media" for uploaded pictures (public to read)
-- ============================================================
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

drop policy if exists "public read media"  on storage.objects;
drop policy if exists "admin upload media" on storage.objects;
drop policy if exists "admin update media" on storage.objects;
drop policy if exists "admin delete media" on storage.objects;

create policy "public read media"  on storage.objects for select using (bucket_id = 'media');
create policy "admin upload media" on storage.objects for insert to authenticated with check (bucket_id = 'media');
create policy "admin update media" on storage.objects for update to authenticated using (bucket_id = 'media');
create policy "admin delete media" on storage.objects for delete to authenticated using (bucket_id = 'media');

-- ============================================================
-- Optional: seed a couple of rows so the site isn't empty on day one
-- ============================================================
insert into public.villas (name, type, location, price, beds, baths, area, status, image_url) values
  ('Royal Residence, Porto Arabia', 'Villa', 'The Pearl, Qatar', 12500000, 6, 7, 850, 'live', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80'),
  ('Sky Penthouse, Marina', 'Penthouse', 'Marina District, Lusail', 7200000, 4, 5, 480, 'live', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80')
on conflict do nothing;
